repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0  # Use the ref you want to point at
  hooks:
    - id: check-executables-have-shebangs
      exclude: 'package/bin/da_ess_contentupdate/|package/bin/splunklib/|venv/'
    - id: check-json
    - id: check-symlinks
    - id: check-yaml
    - id: pretty-format-json
      args: [--autofix]
    - id: flake8
      args: [--max-line-length=131]
      exclude: 'package/bin/da_ess_contentupdate/|package/bin/splunklib/|venv/|package/bin/escu_contextualize.py|package/bin/escu_investigate.py|package/bin/runstory.py|package/bin/detect.py|package/bin/investigate.py|bin/generate.py'
    - id: requirements-txt-fixer
