# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19

dependencies:
  cache_directories:
    - "~/.apt-cache"
  pre:
    - sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial

apt-run: &apt-install
  name: install system packages
  command: |
    sudo apt update -qq
    sudo apt install -y python-dev python3-dev -qq

executors:
  content-executor:
    docker:
      - image: circleci/python:latest
    working_directory: ~/repo

jobs:
  test-api-update:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: checkout repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "" ]; then
                git clone community https://${GITHUB_TOKEN}@github.com/splunk/security-content.git
            else
                git clone --branch ${CIRCLE_BRANCH} https://${GITHUB_TOKEN}@github.com/splunk/security-content.git
            fi
      - run: *apt-install
      - aws-cli/setup:
          profile-name: default
      - run:
          name: update community api sources
          command: |
            cd security-content
            aws s3 cp detection_searches s3://security-content-tmp/detection_searches --recursive --exclude "*" --include "*.yml"
            aws s3 cp story_searches s3://security-content-tmp/story_searches --recursive --exclude "*" --include "*.yml"

workflows:
  version: 2.1
  validate-and-build:
    jobs:
      - test-api-update:
        # build always
          filters:
            tags:
              only: /.*/
