create_time: '2021-01-29T15:14:32.864229Z'
description: Test the disinfection process on a system that is as close to production
  configuration as possible and verify that it works while not damaging any service.
how_to_implement: ''
id: c9d308a0-afab-4fca-adab-9fd5e74e2a99
is_note_required: true
modified_time: '2021-02-23T15:58:54.675864Z'
name: Test
order: 2
owner: null
phase: 25
role: null
sla: null
sla_type: minutes
suggestions:
  actions:
  - deploy patch
  - run script
  - run command
